parameters:
    formio.default.admin_user_id: 14
    formio.default.formiourl_field_name: Form Io Url
    formio.default.formiourl_field_description:  Form io url to insert form
    formio.default.fieldtype_formiourl_identifier: "formio_url"
    formio.default.default_metas:
        author: "Ibexa Community Bundle Form io Bundle"
        copyright: ~
        generator: "Ibexa Platform"
        MSSmartTagsPreventParsing: "TRUE"
    formio.default.dqe_host: 'https://prod2.dqe-software.com/'
    formio.default.dqe_validator:
        enabled: true
        validate_referer: true
        # Set the DQE Licence key to use
        key: '%env(DQE_LICENCE)%'
#formio:
#    system:
#        default:
#            admin_user_id: 14
#            formiourl_field_name: Form Io Url
#            formiourl_field_description: Form io url to insert form
#            fieldtype_formiourl_identifier: "formio_url"
#            default_metas:
#                author: "Ibexa Community Bundle Form io Bundle"
#                copyright: ~
#                generator: "Ibexa Platform"
#                MSSmartTagsPreventParsing: "TRUE"
#            dqe_host: 'https://prod2.dqe-software.com/'
#            dqe_validator:
#                enabled: true
#                validate_referer: true
#                # Set the DQE Licence key to use
#                key: '%env(DQE_LICENCE)%'
