services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mouna\Bundle\formIOBundle\Command\AddFormIoURLCommand: ~
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  Mouna\Bundle\formIOBundle\FieldType\FormIoURL\Type:
    public: true
    tags:
      - { name: ibexa.field_type, alias: formIoURL }

  Mouna\Bundle\formIOBundle\Controller\:
    resource: '../../Controller/*'

  Mouna\Bundle\formIOBundle\Dqe\:
    resource: '../../Dqe/'

  Mouna\Bundle\formIOBundle\Helper\DqeHelper:
    arguments:
      $dqeLicense: '%formio.dqe.license%'
      $dqeHosts: '%formio.dqe.validhosts%'