services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Novactive\Bundle\formIOBundle\Command\AddFormIoURLCommand: ~
  Novactive\Bundle\formIOBundle\Core\Converter\ContentTypesHelper: ~
  Novactive\Bundle\formIOBundle\Core\Installer\Field: ~

  Novactive\Bundle\formIOBundle\Controller\:
    resource: '../../Controller/*'

  Novactive\Bundle\formIOBundle\Dqe\:
    resource: '../../Dqe/'

  Novactive\Bundle\formIOBundle\Helper\DqeHelper:
    arguments:
      $dqeLicense: '%formio.dqe.license%'
      $dqeHosts: '%formio.dqe.validhosts%'