system:
  admin_group:
    field_templates:
      - { template: "@ibexadesign/formIOBundle/fields/content_fields.html.twig" ,priority: 0 }
  site:
    field_templates:
      - { template: "@ibexadesign/formIOBundle/fields/content_fields.html.twig" ,priority: 30 }